### ISSUE TITLE
subscription_id should not be mandatory for .kitchen.yml

### ISSUE THREAD

**Issue by vinyar** [pendrica/kitchen-azurerm#6] opened 2015-10-28 00:14 UTC
Bug: All of the settings for azure are pulled in from the ~/.azure/credentials file.

Subscription ID is one of the settings. The default behavior of the azure-cli is to use the top Subscription if there are multiple subscriptions and default one is not specified.

Current expectation
```
---
driver:
  name: azurerm

driver_config:
  subscription_id: '43e53945-f02b-4269-8854-ad7dd14ac6f2'
  location: 'West Europe'
  machine_size: 'Standard_D1'
```

Expected behavior: subscription id is pulled from credentials file.
```
---
driver:
  name: azurerm

driver_config:
  location: 'West Europe'
  machine_size: 'Standard_D1'
```

**Comment by stuartpreston** [comment] 2015-10-28 04:23
Subscription ID is currently required to be specified as it provides a reference to the correct inifile section. This is intended behaviour/how I designed it. 

Can you elaborate on your use case and why you want to remove subscription_id from the .kitchen.yml? Is this to support multiple subscriptions (one per developer?) in which case can you use the .kitchen.local.yml?

**Comment by vinyar** [comment] 2015-10-28 22:04
In my specific case, each developer has access to 5+ subscriptions (5 minimum). So, when we populate `credentials` file with just one subscription, it would make intuitive sense that driver would use these creds. (that seems to be azure behavior as well, it uses the top subscription by default)

In a dev workstation scenario, each person has to modify .kitchen.yml to specify their subscription id even though it's already defined in the `credentials` file.

**Comment by stuartpreston** [comment] 2015-10-30 21:37
@vinyar Thanks for the explanation, I understand your use case. Will see what can be done (unless someone else submits a PR ;)). But for now you can add your subscription_id to:

- ```.kitchen.yml``` (project config)
- ```.kitchen.local.yml``` (local config)
- ```$HOME/.kitchen/config.yml``` (global config)

**Comment by stuartpreston** [comment] 2016-03-21 17:25
I'm going to close this for now as the current mechanism is used in a few tools and there are workarounds listed in this thread for alternative usages.

**Closed by stuartpreston** 2016-03-21 17:25 UTC
Labels: wontfix

**Comment by vinyar** [comment] 2016-03-22 06:24
:+1:
